AWSTemplateFormatVersion: "2010-09-09"
Description: VPC and Subnet Create

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Project Name Prefix"
        Parameters:
          - Prefix
      - Label:
          default: "Network Configuration"
        Parameters:
          - region

    ParameterLabels:
      region:
        default: "region name"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  Env:
    Type: String
    AllowedValues: ["dev", "pre", "prod"]
    Default: dev

  Prefix:
    Type: String
    Default: "tlsf"

  region:
    Type: String
    Default: "ap-northeast-1"
  #    Default: "us-west-2"

  DBMasterUser:
    Type: String
    Default: "root"

  DBMasterPassword:
    Type: String
    Default: "Password#1"

  # RDSDBSecurityGroupID:
  #   Description: "Select the Security Group ID for RDS."
  #   Type: AWS::EC2::SecurityGroup::Id

Resources:
  RdsSecurityGroupDB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Env}-${Prefix}-sg-db"
      GroupDescription: !Sub "${Env}-${Prefix}-sg-db"
      VpcId:
        Fn::ImportValue: !Sub "${Env}-${Prefix}-vpc"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: "Fn::ImportValue": !Sub "${Env}-${Prefix}-sg-work"
  # -------------------------------------
  # IAM Role
  # -------------------------------------
  RDSMonitoringRole: #RDSの拡張モニタリングの設定ロール
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Env}-${Prefix}-RDSMonitoringRole"
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
  # ------------------------------------------------------------#
  # Amazon RDS for postgres 環境構築
  # ------------------------------------------------------------#

  RDSSubnetGroup: #New OK20241205
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: "Fn::ImportValue": !Sub "${Env}-${Prefix}-db-sub-gp"
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds:
        - "Fn::ImportValue": !Sub "${Env}-${Prefix}-public-subnet-a"
      #        - "Fn::ImportValue": !Sub "${Env}-${Prefix}-private-subnet-c"
      Tags:
        - Key: Name
          Value: "Fn::ImportValue": !Sub "${Env}-${Prefix}-db-sub-gp"
  # -------------------------------------
  # DB ParameterGroup
  # -------------------------------------
  RDSInstanceParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub "${Env}-${Prefix}-rds-pg"
      Family: "postgres17"
      Parameters:
        # SQLの経過時間をログとして残す
        # 1なのでTrue
        log_duration: 1
        # SQLの実行に要した時間をログに記録
        # 10000msもしくはそれ以上長くかかった全てのSQL文がログとして残る
        log_min_duration_statement: 10000
        # どのSQL文をログに記録するか決める。allなので全て
        log_statement: all
        # タイムゾーン
        timezone: Asia/Tokyo

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: 16.6
      DBInstanceIdentifier: !Sub "${Env}-${Prefix}-db" #DB インスタンスの名前
      MasterUsername: !Ref DBMasterUser
      MasterUserPassword: !Ref DBMasterPassword
      DBInstanceClass: "db.t3.micro"
      StorageType: "gp3"
      AllocatedStorage: 20
      MultiAZ: true
      DBSubnetGroupName: !Ref RDSSubnetGroup
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref RdsSecurityGroupDB
      #        - "Fn::ImportValue": !Sub "${Env}-${Prefix}-sg-db"
      DBName: !Sub "${Env}${Prefix}rdsinst"
      #      DBName: !Sub "${Env}-${Prefix}-rds-inst"
      DBParameterGroupName: !Ref RDSInstanceParameterGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "19:00-19:30"
      CopyTagsToSnapshot: true
      StorageEncrypted: true
      EnablePerformanceInsights: true
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt RDSMonitoringRole.Arn
      EnableCloudwatchLogsExports: [postgresql]
      AutoMinorVersionUpgrade: false #マイナーバージョンへのアップグレードの有効化
      PreferredMaintenanceWindow: "sun:20:00-sun:20:30" #システムメンテナンスが可能な時間帯
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: !Sub "${Env}-${Prefix}-db-a"

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  RDSInstance:
    Value: !Ref RDSInstance
    Export:
      Name: !Sub "${Env}-${Prefix}-db-a"
